Feature/farms portfolio
trisolaris-labs/interface pull request #139
Opened 2022-01-21 05:47 UTC by memacius32

Adding Farms portfolio:
 - Total currently deposited in farms.
 - Total rewards by token.

2022-01-24 19:25 UTC, specialist0x commented on src/components/earn/FarmBanner/index.tsx
> +  const isDualRewards = chefVersion === 1
This is `==` on the other file -- is the response always a number?

2022-01-24 19:27 UTC, specialist0x commented on src/components/earn/FarmBanner/index.tsx
> +  const parsedToken = token ? token : 'ZERO'
```suggestion
  const parsedToken = token ?? 'ZERO'
```

2022-01-24 19:37 UTC, specialist0x commented on src/components/earn/FarmBanner/index.tsx
> +        for (var prop in n) {
nit

```suggestion
        for (let prop in n) {
```

2022-01-25 00:43 UTC, specialist0x commented on src/components/earn/FarmBanner/index.tsx
> +                      <StyledSummaryHeader> Your total unreclaimed tokens:</StyledSummaryHeader>
```suggestion
                      <StyledSummaryHeader> Your total unclaimed tokens:</StyledSummaryHeader>
```

2022-01-25 00:44 UTC, specialist0x commented on src/components/earn/FarmBanner/index.tsx
> +                      <StyledSummaryHeader> Your total unreclaimed tokens:</StyledSummaryHeader>
Maybe "Claimable tokens:"

2022-01-25 00:45 UTC, specialist0x commented on src/pages/EarnTri/index.tsx
> +
These look like they're unused

2022-01-25 00:45 UTC, specialist0x commented on src/data/TotalStakedInPool.ts
> +
This doesn't need to be part of this diff, right?

2022-01-25 00:45 UTC, specialist0x commented on src/pages/EarnTri/Manage.tsx
> +
This doesn't need to be part of this diff, right?

2022-01-25 01:09 UTC, specialist0x requested changes

2022-01-25 01:09 UTC, specialist0x commented on src/components/earn/FarmBanner/FarmBanner.types.ts
> +}
Is there a reason this needs to be `key`'d? If these items were pushed as objects in to an array, could the portfolio balance show the sum of all items in the array

It'd make managing a flat data structure easier, too

2022-01-25 01:09 UTC, specialist0x commented on src/components/earn/FarmBanner/index.tsx
> +    if (!countEnabled) {
This seems hacky

2022-01-25 01:09 UTC, specialist0x commented on src/components/earn/FarmBanner/index.tsx
> +    if (!countEnabled) {
If a pool exists its balance should be checked, no?

2022-02-04 06:33 UTC, memacius32 commented
Replaced by #146, Closing.

2022-02-04 06:33 UTC, closed without merging