New farms UI
trisolaris-labs/interface pull request #396
Opened 2022-10-03 11:58 UTC by memacius32

Main branch PR for new farms ui. 
 Contains all approved pr's:
- Collapsed UI
- Expanded UI
- Removing Farm groups

<img width="1493" alt="Screen Shot 2022-10-03 at 13 55 10" src="https://user-images.githubusercontent.com/96993065/193571021-2c1d9faa-f68e-4011-b9a8-e321e2ed6d1c.png">

2022-10-07 10:33 UTC, memacius32 commented
Ready to review!.  Preview approved PR's are included until commit [d340dfc](https://github.com/trisolaris-labs/interface/pull/396/commits/d340dfc3720efaf465c9ff9e376e0cd78a2a8580)

2022-10-11 20:32 UTC, specialist0x commented
This looks incredible!  Only UI issue I saw is:

When clicking deposit, `50%` has either `:active` or `:focus`: 
<img width="183" alt="image" src="https://user-images.githubusercontent.com/94581898/195192056-e82fe390-7abc-4bd9-bbb5-28b6736fe1cc.png">

Not sure if this is fixed on a different PR

2022-10-11 20:32 UTC, specialist0x commented on src/components/Toggle/index.tsx
> +  padding: ${({ padding }) => (padding ? padding : '0.35rem 0.6rem')};
```suggestion
  padding: ${({ padding }) => (padding ?? '0.35rem 0.6rem')};
```

2022-10-11 20:33 UTC, specialist0x commented on src/components/earn/PoolCardTri/ManageStake.tsx
> +    event.stopPropagation()
Shouldn't `event.stopPropagation()` come _first_ in all of these, in order to prevent race conditions?

2022-10-11 20:34 UTC, specialist0x commented on src/components/earn/PoolCardTri/ClaimRewardModalTri.tsx
> +      if (stakingContractv2 && stakedAmount) {
Else if?

2022-10-11 20:38 UTC, specialist0x commented on src/components/Toggle/index.tsx
> +  toggle: (event: React.MouseEvent) => void
```suggestion
  toggle: () => void
```

2022-10-11 20:39 UTC, specialist0x commented on src/components/Toggle/index.tsx
> +  padding?: string
```suggestion
  padding?: string,
  stopPropagation?: boolean
```

2022-10-11 20:39 UTC, specialist0x commented on src/components/Toggle/index.tsx
> +  padding,
```suggestion
  padding,
  stopPropagation,
```

2022-10-11 20:40 UTC, specialist0x commented on src/components/Toggle/index.tsx
>      <StyledToggle id={id} isActive={isActive} onClick={toggle} {...otherProps}>
This way, you don't need to add it on every handler, and it's called consistently on every instance

2022-10-11 20:40 UTC, specialist0x commented on src/components/earn/PoolCardTri/ManageStake.tsx
> +    event.stopPropagation()
See above changes to `<Toggle />`

2022-10-11 20:46 UTC, specialist0x commented on src/components/earn/PoolCardTri/index.tsx
> +    event.stopPropagation()
Should `stopPropagation` happen first?

2022-10-11 20:49 UTC, specialist0x requested changes
Great stuff, only minor things

2022-10-13 13:41 UTC, memacius32 commented on src/components/Toggle/index.tsx
>      <StyledToggle id={id} isActive={isActive} onClick={toggle} {...otherProps}>
Great idea!

2022-10-13 13:56 UTC, memacius32 commented on src/components/earn/PoolCardTri/index.tsx
> +    event.stopPropagation()
Inverted

2022-10-13 14:05 UTC, memacius32 commented
Addressed and implemented suggested changes, also merged main

2022-10-26 14:57 UTC, specialist0x commented on src/components/Toggle/index.tsx
> +  padding: 0.35rem 0.7rem;
0.6 to 0.7 was intentional?

2022-10-26 14:58 UTC, specialist0x commented on src/components/earn/PoolCardTri/ClaimRewardModalTri.tsx
> +          console.log(error)
Also -- either use `async/await` _or_ `.then / .catch`, antipattern to use both

2022-10-26 15:00 UTC, specialist0x approved these changes
Great work, @memacius32 ! 

Approving, but since this is a large PR, please don't merge/rebase in to `main` until we're ready to launch this feature.

2022-11-29 21:16 UTC, merged